"""
Knowledge Base loader — reads from a directory of .xlsx files OR a single .xlsx file,
splits documents by language (en / zh_hant), and builds per-language FAISS indexes.

Embeddings are generated by calling the HuggingFace TEI embedding service (TEI_EMBED_URL).
FAISS index runs on CPU in the main application container.

Column layout expected in each worksheet (row 1 = header):
  [0] No.        [1] Source     [2] lang       [3] definition
  [4] question   [5] answer     [6] category   [7] active   [8] status
"""

from __future__ import annotations

import os
import pickle
from pathlib import Path

import faiss
import httpx
import numpy as np
import openpyxl
from dotenv import load_dotenv

load_dotenv(Path(__file__).parent / ".env")

CACHE_DIR = Path(__file__).parent / "cache"
TEI_EMBED_URL = os.getenv("TEI_EMBED_URL", "http://embedding:80")


def _resolve_kb_path() -> Path:
    """Resolve KB_PATH from .env relative to this file's directory."""
    raw = os.getenv("KB_PATH", "../FAQ_combined")
    p = Path(raw)
    if not p.is_absolute():
        p = (Path(__file__).parent / p).resolve()
    return p


TEI_EMBED_BATCH_SIZE = int(os.getenv("TEI_EMBED_BATCH_SIZE", "32"))


def _tei_embed_sync(texts: list[str]) -> np.ndarray:
    """Call TEI /embed synchronously in batches — used at startup when building the index."""
    all_embeddings: list[np.ndarray] = []
    with httpx.Client(timeout=120.0) as client:
        for i in range(0, len(texts), TEI_EMBED_BATCH_SIZE):
            batch = texts[i : i + TEI_EMBED_BATCH_SIZE]
            resp = client.post(
                f"{TEI_EMBED_URL}/embed",
                json={"inputs": batch, "normalize": True, "truncate": True},
            )
            resp.raise_for_status()
            all_embeddings.append(np.array(resp.json(), dtype=np.float32))
    return np.vstack(all_embeddings)


async def tei_embed_async(texts: list[str]) -> np.ndarray:
    """Call TEI /embed asynchronously — used at query time."""
    async with httpx.AsyncClient(timeout=30.0) as client:
        resp = await client.post(
            f"{TEI_EMBED_URL}/embed",
            json={"inputs": texts, "normalize": True, "truncate": True},
        )
        resp.raise_for_status()
    return np.array(resp.json(), dtype=np.float32)


def _load_xlsx(file_path: Path) -> tuple[list[dict], list[dict]]:
    """Parse a single xlsx file and return (en_docs, zh_docs)."""
    en_docs: list[dict] = []
    zh_docs: list[dict] = []

    wb = openpyxl.load_workbook(file_path, read_only=True, data_only=True)
    for ws in wb.worksheets:
        for row in ws.iter_rows(min_row=2, values_only=True):
            if not any(row):
                continue

            lang     = row[2] if len(row) > 2 else None
            question = row[4] if len(row) > 4 else None
            answer   = row[5] if len(row) > 5 else None
            active   = row[7] if len(row) > 7 else True

            if active is False:
                continue
            if not question or not answer:
                continue

            doc = {
                "q":          str(question).strip(),
                "answer":     str(answer).strip(),
                "source":     str(row[1]).strip() if row[1] else "",
                "definition": str(row[3]).strip() if row[3] else "",
                "lang":       lang,
            }

            if lang == "en":
                en_docs.append(doc)
            elif lang == "zh_hant":
                zh_docs.append(doc)

    wb.close()
    return en_docs, zh_docs


def load_all_docs() -> tuple[list[dict], list[dict]]:
    kb_path = _resolve_kb_path()
    xlsx_files: list[Path] = []

    if kb_path.is_dir():
        xlsx_files = sorted(kb_path.glob("*.xlsx"))
        if not xlsx_files:
            raise FileNotFoundError(f"No .xlsx files found in directory: {kb_path}")
    elif kb_path.is_file():
        xlsx_files = [kb_path]
    else:
        candidate = kb_path.with_suffix(".xlsx")
        if candidate.is_file():
            xlsx_files = [candidate]
        else:
            raise FileNotFoundError(
                f"Knowledge base not found at '{kb_path}'. "
                "Set KB_PATH in .env to a directory of .xlsx files or a single .xlsx file."
            )

    all_en: list[dict] = []
    all_zh: list[dict] = []
    for f in xlsx_files:
        print(f"  Loading {f.name}…")
        en, zh = _load_xlsx(f)
        all_en.extend(en)
        all_zh.extend(zh)

    print(f"Loaded {len(all_en)} EN docs and {len(all_zh)} ZH docs from {len(xlsx_files)} file(s).")
    return all_en, all_zh


class KnowledgeBase:
    def __init__(self):
        print(f"KnowledgeBase init  [TEI embed: {TEI_EMBED_URL}]")

        self.en_docs: list[dict] = []
        self.zh_docs: list[dict] = []
        self.en_index: faiss.Index | None = None
        self.zh_index: faiss.Index | None = None

        self._load_or_build()

    def _build_index(self, docs: list[dict]) -> faiss.Index:
        texts = [f"{doc['q']} {doc['answer']}" for doc in docs]
        print(f"    Encoding {len(texts)} documents via TEI…")
        embeddings = _tei_embed_sync(texts)
        index = faiss.IndexFlatIP(embeddings.shape[1])
        index.add(embeddings)
        return index

    def _load_or_build(self) -> None:
        CACHE_DIR.mkdir(exist_ok=True)
        en_idx = CACHE_DIR / "en_index.faiss"
        zh_idx = CACHE_DIR / "zh_index.faiss"
        en_pkl = CACHE_DIR / "en_docs.pkl"
        zh_pkl = CACHE_DIR / "zh_docs.pkl"

        if all(p.exists() for p in [en_idx, zh_idx, en_pkl, zh_pkl]):
            print("Loading cached FAISS indexes…")
            self.en_index = faiss.read_index(str(en_idx))
            self.zh_index = faiss.read_index(str(zh_idx))
            with open(en_pkl, "rb") as f:
                self.en_docs = pickle.load(f)
            with open(zh_pkl, "rb") as f:
                self.zh_docs = pickle.load(f)
            print(f"  EN: {len(self.en_docs)} docs | ZH: {len(self.zh_docs)} docs")
        else:
            print("Building knowledge base from source files…")
            self.en_docs, self.zh_docs = load_all_docs()

            print("  Building EN index…")
            self.en_index = self._build_index(self.en_docs)
            print("  Building ZH index…")
            self.zh_index = self._build_index(self.zh_docs)

            faiss.write_index(self.en_index, str(en_idx))
            faiss.write_index(self.zh_index, str(zh_idx))
            with open(en_pkl, "wb") as f:
                pickle.dump(self.en_docs, f)
            with open(zh_pkl, "wb") as f:
                pickle.dump(self.zh_docs, f)
            print("FAISS indexes saved to cache.")

    async def search(self, query: str, lang: str, top_k: int) -> list[dict]:
        """Async dense retrieval — embeds query via TEI, searches FAISS on CPU."""
        if lang == "zh_hant":
            index, docs = self.zh_index, self.zh_docs
        else:
            index, docs = self.en_index, self.en_docs

        if index is None or not docs:
            return []

        top_k = min(top_k, len(docs))
        query_vec = await tei_embed_async([query])
        _, indices = index.search(query_vec, top_k)
        return [docs[i] for i in indices[0] if i < len(docs)]
